### ISSUE TITLE
about StringUtils.sol

### ISSUE THREAD

**Issue by yukiexe** [Andoromeda-Foundation/LeBlock#1]
我發現了這篇文章用兩種方法做了gas 使用量研究
用 SHA3 比較省
https://github.com/ltfschoen/dex/commit/36583c0b64311b6cdc3264c8cc61df989b334317

改成這樣？
function compareStrings (string a, string b) view returns (bool){
       return keccak256(a) == keccak256(b);
   }

**Comment by flyq** [comment]
好的，我看一下那篇。
然后直接对memory类型的string和storage类型的string对比，会报错，用keccak256转化一下可能都变成了memory类型，不清楚行不行。明天试试

**Comment by flyq** [comment]
keccak256(abi.encodePacked(ipfsAddrOf[0])) != keccak256(abi.encodePacked(_ipfsAddr))

这样是可以的

**Comment by flyq** [comment]
但是我不清楚既然可以通过上面这种检查hash的方法来看两个不同存储类型的string是否相同，为什么搜索结果大部分是遍历整个字符串。。。

**Comment by flyq** [comment]
https://forum.ethereum.org/discussion/3238/string-compare-in-solidity第二个哥们讲了只有把它们的值赋给新建memory变量，然后再比较也可以

**Comment by yukiexe** [comment]
@flyq 最早這段code出現在 15年的文章裡面，可能那時候沒有 hash 方法可以用，然後就被一直傳了
